### ISSUE TITLE
EfCore 1.1?

### ISSUE THREAD

**Issue by ry8806** [mwhelan/MvcEfCore10Sample#1]
Hi, didn't know where to put this question so I thought I'd leave an "Issue" here

I found your post (http://www.michael-whelan.net/ef-core-101-migrations-in-separate-assembly/) really useful, however I was wondering if this can be directly ported to EFCore 1.1??
I'm looking to do the same, and google isn't returning many results for EFCore 1.1 so wondered if you've upgraded yet?

Thanks

**Comment by mwhelan** [comment]
Hi @ry8806 . You can leave comments on the site, but this is fine too... :-) 

Yes, it can be ported to EF Core 1.1. I've updated the sample in this repo to .Net Core 1.1 and EF Core 1.1 and works fine.

**Comment by ry8806** [comment]
thanks, I did see someone else [commented](http://disq.us/p/1f6pibm) but it didn't look like they got a reply!

brilliant! I was having trouble, it turned out to be that they'd changed the name of the tools (added ".DotNet") to the end - lesson learned - always read the release notes!!

Thanks for a brilliant post - it helped massively!
